import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.186.0/build/three.module.js';

export class Renderer{
 constructor(canvas){this.canvas=canvas;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x17100b);this.camera=new THREE.PerspectiveCamera(42,1,.1,100);this.camera.position.set(0,-7.2,7.3);this.camera.lookAt(0,.8,0);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.root=new THREE.Group();this.scene.add(this.root);this.cards=new Map();this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.cardScale=1;this.setup();this.resize();addEventListener('resize',()=>this.resize());this.canvas.addEventListener('webglcontextlost',e=>e.preventDefault());this.canvas.addEventListener('webglcontextrestored',()=>this.rebuild=true);this.frame()}
 setup(){const amb=new THREE.HemisphereLight(0xffecd2,0x24160d,2.2);this.scene.add(amb);const key=new THREE.DirectionalLight(0xffe5c7,3.2);key.position.set(-3,-4,9);key.castShadow=true;key.shadow.mapSize.set(1024,1024);this.scene.add(key);const floor=new THREE.Mesh(new THREE.BoxGeometry(20,15,.55),new THREE.MeshStandardMaterial({color:0x3b2418,roughness:.72}));floor.position.set(0,1,-.4);floor.receiveShadow=true;this.root.add(floor);const felt=new THREE.Mesh(new THREE.BoxGeometry(17,12,.18),new THREE.MeshStandardMaterial({color:0x20352a,roughness:.92}));felt.position.set(0,1,-.08);felt.receiveShadow=true;this.root.add(felt)}
 resize(){const w=innerWidth,h=innerHeight;const short=Math.min(w,h);this.cardScale=short<600?1.42:short<900?1.22:1;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 texture(c){const cn=document.createElement('canvas');cn.width=300;cn.height=420;const x=cn.getContext('2d');x.fillStyle='#eee3ce';x.fillRect(0,0,300,420);x.strokeStyle='#80684e';x.lineWidth=7;x.strokeRect(8,8,284,404);x.fillStyle='#211710';x.textAlign='center';x.font='bold 112px system-ui';x.fillText(c.number,150,165);x.font='92px serif';x.fillText({cross:'✚',triangle:'△',square:'□',diamond:'◇'}[c.suit],150,285);return new THREE.CanvasTexture(cn)}
 make(c){const g=new THREE.BoxGeometry(.92,1.3,.14),m=new THREE.MeshStandardMaterial({color:0xece0ca,roughness:.5});const o=new THREE.Mesh(g,m);o.scale.setScalar(this.cardScale);o.castShadow=true;o.userData.id=c.id;const f=new THREE.Mesh(new THREE.PlaneGeometry(.82,1.18),new THREE.MeshBasicMaterial({map:this.texture(c),transparent:true}));f.position.z=.076;o.add(f);return o}
 clearCards(){for(const o of this.cards.values()){o.traverse(v=>{if(v.isMesh){v.geometry.dispose();if(v.material.map)v.material.map.dispose();v.material.dispose()}});this.root.remove(o)}this.cards.clear()}
 render(s,dragId=null,previewIndex=null){if(this.rebuild){this.clearCards();this.rebuild=false}this.clearCards();const all=[];const tableY=1.15;const spacing=Math.min(1.02,10/Math.max(1,s.table.length));const start=-(s.table.length-1)*spacing/2;s.table.forEach((c,i)=>{const o=this.make(c);o.position.set(start+i*spacing,tableY,0);this.root.add(o);this.cards.set(c.id,o);all.push(o)});const handStart=-(s.hand.length-1)*.53/2;s.hand.forEach((c,i)=>{const o=this.make(c);const t=i/(s.hand.length-1||1);o.position.set(handStart+i*.53,-2.55,.15+Math.sin(t*Math.PI)*.1);o.rotation.z=(t-.5)*.10;this.root.add(o);this.cards.set(c.id,o);all.push(o)});if(dragId&&this.cards.has(dragId)){const o=this.cards.get(dragId);o.position.y=-.15;o.position.z=.8;o.scale.setScalar(this.cardScale*1.04)}if(previewIndex!=null&&s.table.length){const gapX=start+previewIndex*spacing;const marker=new THREE.Mesh(new THREE.BoxGeometry(.055,1.05,.035),new THREE.MeshStandardMaterial({color:0xd9c19a,transparent:true,opacity:.55}));marker.position.set(gapX,tableY,.12);this.root.add(marker)}}
 pick(x,y){const r=this.canvas.getBoundingClientRect();this.pointer.x=((x-r.left)/r.width)*2-1;this.pointer.y=-((y-r.top)/r.height)*2+1;this.ray.setFromCamera(this.pointer,this.camera);for(const h of this.ray.intersectObjects([...this.cards.values()],true)){let o=h.object;while(o&&!o.userData.id)o=o.parent;if(o?.userData.id)return o.userData.id}return null}
 tableIndex(x,s){if(!s.table.length)return 0;const r=this.canvas.getBoundingClientRect();const nx=(x-r.left)/r.width;return Math.max(0,Math.min(s.table.length,Math.round(nx*s.table.length)))}
 frame=()=>{requestAnimationFrame(this.frame);this.renderer.render(this.scene,this.camera)}}

export {THREE};
